server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|json|webmanifest|png|jpg|jpeg|gif|webp|ico|svg|mp4|mp3|woff|woff2|ttf)$ {
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public";
    }
}
